# Generated by Django 4.0 on 2022-06-14 15:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=user.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
