# Generated by Django 4.0 on 2022-06-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role_user_role_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
