# Generated by Django 4.0 on 2022-06-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_role_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
