# Generated by Django 4.0 on 2022-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_role_id_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_back_side',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship_front_side',
            field=models.BinaryField(null=True),
        ),
    ]
