# Generated by Django 4.0 on 2022-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_citizenship_back_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
