# Generated by Django 4.0 on 2022-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0023_alter_product_date_created'),
        ('user', '0010_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(db_column='category_id', null=True, related_name='+', to='clg_api.Category'),
        ),
    ]
