# Generated by Django 4.0 on 2022-06-14 15:31

import clg_api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_at', models.DateField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.BinaryField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_at', models.DateField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 170693), null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_at', models.DateField(default=datetime.datetime(2022, 6, 14, 21, 16, 1, 167702))),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
