# Generated by Django 4.0 on 2022-06-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 188523), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 42, 6, 185567)),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
