# Generated by Django 4.0 on 2022-06-14 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0002_alter_customer_creaed_at_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 122520), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 14, 21, 44, 59, 120526)),
        ),
    ]
