# Generated by Django 4.0 on 2022-06-16 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
        ('clg_api', '0005_alter_customer_creaed_at_alter_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user', verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
        migrations.AlterField(
            model_name='order',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user', verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
        migrations.AlterField(
            model_name='product',
            name='creaed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user', verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 30654), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2022, 6, 16, 7, 54, 24, 28660)),
        ),
    ]
