# Generated by Django 4.0 on 2022-06-23 18:21

import clg_api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0006_alter_customer_creaed_at_alter_customer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='creaed_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='creaed_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creaed_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 0, 6, 3, 477851), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=clg_api.models.MyCustomField(null=True),
        ),
    ]
