# Generated by Django 4.0 on 2022-07-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0018_alter_product_date_created_alter_category_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 14, 42, 14, 743101), null=True),
        ),
    ]
