# Generated by Django 4.0 on 2022-07-05 21:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clg_api', '0020_alter_product_date_created_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 3, 24, 47, 679795), null=True),
        ),
    ]
