# Generated by Django 4.0 on 2022-07-05 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0022_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 3, 27, 21, 224864), null=True),
        ),
    ]
