# Generated by Django 4.0 on 2022-07-06 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0029_remove_product_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Delivered'), ('1', 'pending')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 11, 41, 43, 671772), null=True),
        ),
    ]
