# Generated by Django 4.1.3 on 2022-11-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuent',
        ),
    ]
