# Generated by Django 4.1.3 on 2022-11-03 03:10

import clg_api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.BinaryField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('manufactured_date', models.DateField(default=datetime.datetime(2022, 11, 3, 8, 55, 26, 701871), null=True)),
                ('photo', models.BinaryField(null=True)),
                ('status', models.CharField(choices=[('0', 'Delivered'), ('1', 'pending')], default='1', max_length=20)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
