# Generated by Django 4.1.3 on 2022-11-03 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 8, 56, 41, 4910), null=True),
        ),
    ]
