# Generated by Django 4.1.3 on 2022-11-03 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0003_alter_product_manufactured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 3, 3, 13, 58, 626748, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
