# Generated by Django 4.1.3 on 2022-11-03 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0004_alter_product_manufactured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 9, 0, 21, 940096), null=True),
        ),
    ]
