# Generated by Django 3.2.9 on 2021-11-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstock', '0002_auto_20211123_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
